# Generated by Django 4.2 on 2023-04-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateField(default='2023-04-14'),
            preserve_default=False,
        ),
    ]
