# Generated by Django 4.2 on 2023-04-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='today',
            field=models.DateField(auto_now=True),
        ),
    ]
