# Generated by Django 4.2 on 2023-04-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='today',
        ),
    ]
