# Generated by Django 4.2 on 2023-04-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_post_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Dday',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
