# Generated by Django 4.2 on 2023-04-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_dday'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Done',
            field=models.BooleanField(default=False),
        ),
    ]
